### ISSUE TITLE
script error

### ISSUE THREAD

**Issue by kashish11** [numixproject/numix-folders#116] opened 2015-09-15 09:51 UTC
I entered `cd /var/numix-folders` and then `sudo ./numix-folders` and received the output `./numix-folders: line 106: /opt/numix-folders/gui/gui: No such file or directory`. 

I'm on ubuntu 15.04 unity. I've installed via PPA.

Simply running `numix folders` in terminal asks for password and then returns nothing.

**Comment by wa4557** [comment] 2015-09-15 09:52
Yeah the packaging doesn't work anymore, there are several bugs that needs to be solved. For now you can run `numix-folders -t`

**Comment by Foggalong** [comment] 2015-09-15 09:55
Thus is a duplicate of #113

**Closed by Foggalong** 2015-09-15 09:55 UTC
