### ISSUE TITLE
problem with case conversion?

### ISSUE THREAD

**Issue by jamdox** [numixproject/numix-folders#152] opened 2016-02-26 21:43 UTC
Was getting "Oops...colour" error.  Might have fixed it by commenting out line 159 of numix-folders script.

Zsh.

**Comment by wa4557** [comment] 2016-03-20 14:31
Cannot reproduce this. What did you type in as colour when asked?

**Comment by jamdox** [comment] 2016-04-15 05:36
`blue`

**Comment by wa4557** [comment] 2016-04-15 07:04
still not reproducible for me. When running `numix-folders` with `zsh``and selecting `blue` everything works fine

What does `echo "$(tr '[:upper:]' '[:lower:]' <<< "blue")"` give you?

**Comment by Foggalong** [comment] 2016-06-19 20:42
Closing since without more information we can't fix it :(

**Closed by Foggalong** 2016-06-19 20:42 UTC
Labels: bug, invalid
