### ISSUE TITLE
numix-folders not working on fedora 23

### ISSUE THREAD

**Issue by maxpro4u** [numixproject/numix-folders#128] opened 2015-10-28 17:23 UTC
I tried using sudo and beesu. Here is output
[max@max numix]$ sudo numix-folders
[sudo] password for max: 
sudo: numix-folders: command not found
[max@max numix]$ su
Password: 
[root@max numix]# numix-folders
bash: numix-folders: command not found...﻿
beesu '/home/max/Downloads/numix/numix-folders' 
touch: cannot touch ‘/home/root/.config/numix-folders’: No such file or directory
sed: can't read /home/root/.config/numix-folders: No such file or directory
sed: can't read /home/root/.config/numix-folders: No such file or directory
sed: can't read /home/root/.config/numix-folders: No such file or directory
sed: can't read /home/root/.config/numix-folders: No such file or directory
sed: can't read /home/root/.config/numix-folders: No such file or directory
gtk-update-icon-cache: Cache file created successfully.
gtk-update-icon-cache: The generated cache was invalid.
Folder change complete!
/home/max/Downloads/numix/numix-folders: line 321: /home/root/.config/numix-folders: No such file or directory
chown: cannot access ‘/home/root/.config/numix-folders’: No such file or directory﻿

**Comment by wa4557** [comment] 2015-10-28 17:53
What does `which numix-folders` and `ls /usr/bin/numix-folders` give?

**Comment by maxpro4u** [comment] 2015-10-28 18:19
[max@max ~]$ which numix-folders
/usr/bin/which: no numix-folders in (/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/max/.local/bin:/home/max/bin)
[max@max ~]$ ls /usr/bin/numix-folders
ls: cannot access /usr/bin/numix-folders: No such file or directory

**Comment by wa4557** [comment] 2015-10-28 18:54
Ok so how did you install numix-folders then?

**Comment by maxpro4u** [comment] 2015-10-28 19:26
I used the paolorotolo numix repo

**Comment by wa4557** [comment] 2015-10-28 19:31
Ok I don't know if and how this repo works, but it seems that the script is not in your `$PATH` and thus cannot be executed. Try to `cd` into the folder of te script and run `./numix-folders`

**Comment by maxpro4u** [comment] 2015-10-28 19:39
I am going to add the copr repo and reinstall

**Comment by Foggalong** [comment] 2015-10-28 19:47
CC @PaoloRotolo

**Comment by maxpro4u** [comment] 2015-10-28 20:08
reinstalling using the copr repo didn't help. the dir is still not there

**Comment by mikpouet** [comment] 2015-11-11 23:39
The script didn't work for me either on Fedora 23 using the dnf install (error building the cache in Numix-Circle) but it's working with files from github. I replaced manually the Numix and Numix-Circle folders in `/usr/share/icons` with those I got here with a git clone and launched the script from the download folder with `sudo ./numix-folders`. You have to match one of the path inside the script so the 2 folders can also be in `~/.local/share/icons`.

**Comment by mikpouet** [comment] 2015-11-11 23:54
fyi numix-folder is not on the repo. @maxpro4u after reinstalling the files from github, as @wa4557 said you need to give the script the folder context by `cd /home/max/Downloads/numix/numix-folders` and launch the script with `./numix-folders`.

**Comment by bil-elmoussaoui** [comment] 2016-01-01 14:30
I can confirm what @maxpro4u There's no package named numix-folders in the repo. I think that @maxpro4u thought that numix-folders is installed automatically when you do install the numix-icon-theme package.

**Comment by bil-elmoussaoui** [comment] 2016-11-05 19:38
ping @Foggalong

**Comment by Foggalong** [comment] 2016-11-05 19:49
I'm not entirely sure who does the packaging for Fedora. I'll ask in the chat

**Comment by Foggalong** [comment] 2020-03-20 16:37
The COPR repo has long since been abandoned so closing this now :eyes:

**Closed by Foggalong** 2020-03-20 16:37 UTC
Labels: bug
