### ISSUE TITLE
Not working on Arch + Gnome 3.24.2

### ISSUE THREAD

**Issue by dvorapa** [numixproject/numix-folders#175] opened 2017-06-24 16:21 UTC
GUI:
```
> sudo numix-folders
No protocol specified
Unable to init server: Could not connect: Connection refused
No protocol specified
Unable to init server: Nelze se připojit: Connection refused
No protocol specified
Unable to init server: Nelze se připojit: Connection refused

(numix-folders:2180): Gtk-WARNING **: cannot open display: :0
```
Terminal:
Reported in #160

**Comment by ludenticus** [comment] 2018-03-06 15:56
This isn't a bug. It is the intended behavior of Wayland. Run `sudo numix-folders --cli` instead. Or login with `xorg`.

**Comment by palob** [comment] 2018-03-10 22:45
Can be closed in favour of #162.

**Closed by palob** 2018-03-10 22:45 UTC
Labels: bug
