### ISSUE TITLE
keep numix-folers setting when updating

### ISSUE THREAD

**Issue by idmresettrial** [numixproject/numix-folders#99] opened 2015-07-03 00:54 UTC
Hi Numix devs,
First, I would like to say thanks to all of you for designing a wonderful project.

I have a small issue need your help: everytime I update numix-folder, the setting (folder style and the color) is reset. Is there any way to keep the setting everytime?

Thanks and Best Regards!

ps: I use Ubuntu 15.04 64-bit.

**Comment by dirtydancing** [comment] 2015-07-17 07:28
This is arguably a duplicate of https://github.com/numixproject/numix-folders/issues/45 and thus would currently be a won't fix.

Possibly there is a way to somehow save the settings within a possible GUI/colour picker enhancement, cf. also this comment https://github.com/numixproject/numix-folders/issues/47#issuecomment-113933833.

**Closed** 2015-07-17 09:55 UTC
Labels: duplicate

**Comment by idmresettrial** [comment] 2015-07-18 03:29
I have an idea: What if we set +i flag for the folder icons ? (chattr +i /path/to/folder_icons)
@dirtydancing

**Comment by dirtydancing** [comment] 2015-07-18 08:24
Interesting idea. I am not sure if `chattr +i` is a suitable approach, though. Would that mean that users would not be able to change the folder style/colour anymore unless they remove this attribute before? And would this mean that removing this attribute and adding it back again would have to be part of every folder style/colour change via numix-folders?

This would have to relate to the folder icons in Numix base as well as to the file manager app icons in Numix-Circle. Both get "reset" whenever Numix base and/or Numix-Circle are updated, e.g. via PPA.

I can tell from various issue reports about somehow keeping or saving the user settings for numix-folders that it would be useful to address this, apart from the present issue cf. https://github.com/numixproject/numix-folders/issues/45, https://github.com/numixproject/numix-folders/issues/64, https://github.com/numixproject/numix-folders/issues/47#issuecomment-113933833.

@wa4557 @PaoloRotolo Any ideas on this one?

**Comment by idmresettrial** [comment] 2015-07-20 01:44
I've had a completely solution for this on my Ubuntu 15.04. You may want to have a look, at https://github.com/idmresettrial/numix-folders-autorun
@dirtydancing

**Comment by dirtydancing** [comment] 2015-07-20 07:14
@idmresettrial Sweet! I will have a look at it. This might be a little while.

**Comment by Foggalong** [comment] 2015-07-20 11:02
This looks cool, but the problem is that the solution has to work on any distro :(

**Comment by idmresettrial** [comment] 2015-07-21 01:16
I think every distro family has a way to run a script after package updating finished.
@Foggalong

**Comment by dirtydancing** [comment] 2015-07-23 12:18
Cf. the further discussion over at https://github.com/numixproject/numix-folders/issues/101.

**Comment by dirtydancing** [comment] 2015-07-27 16:29
@idmresettrial I have run your script on Xubuntu 15.04 (VM), and it has worked for style 5, color blue, after I edited the autorun .config file accordingly :+1: 

Checked with a Numix base update via PPA. Originally, I wanted to check whether this also works when Numix-Circle is updated via PPA, but unfortunately there is a problem with the Numix-Circle PPA updates, cf. https://github.com/numixproject/numix-icon-theme-circle/issues/2430.

I am wondering though: would this also work for custom colours? This would mean entering "custom" for colour and then hex values for the primary, secondary and symbol colours (colour1, colour2, colour3).

**Comment by idmresettrial** [comment] 2015-07-27 18:09
@dirtydancing: Certainly it will work with custom color, but need some fixes in the script. ^^

**Comment by dirtydancing** [comment] 2015-07-27 18:54
I see :) No need to get into this at this point I guess, as it looks like the encompassing official Numix approach to this will be done via a GUI which will also contain a colour picker, cf. https://github.com/numixproject/numix-folders/issues/101, https://github.com/numixproject/numix-folders/issues/102.

Personally, I am on Arch/GNOME, I was just wondering, as I assume many Numix users use the PPA.

**Comment by idmresettrial** [comment] 2015-07-29 11:27
@dirtydancing : Have you tried fixing my script for your Arch system? :)

**Comment by dirtydancing** [comment] 2015-07-29 13:09
Nope. I am afraid this exceeds my current expertise.
