### ISSUE TITLE
Rerun script on every numix-theme update

### ISSUE THREAD

**Issue by uloco** [numixproject/numix-folders#64] opened 2015-05-04 06:04 UTC
I have to rerun this script everytime when there is a new update on `numix-icon-theme`. 
Is there a way to automate this or any other workaround?

**Comment by dirtydancing** [comment] 2015-05-04 08:22
I think this is a duplicate of https://github.com/numixproject/numix-folders/issues/45 :), so this is arguably a `wontfix`.

**Closed** 2015-05-04 09:26 UTC
Labels: duplicate

**Comment by dirtydancing** [comment] 2015-07-23 12:20
Cf. the further discussion over at #101.
