### ISSUE TITLE
GUI application name of Numix-Folders currently is "Gui" instead of "Numix-Folders"

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-folders#132] opened 2015-12-11 12:11 UTC
The GUI application name of Numix-Folders currently is `Gui`, cf. screenshot below. This should probably be `Numix-Folders` or the like instead. Arch/GNOME, AUR `numix-folders-git` package.

@wa4557 Any ideas?

![gui](https://cloud.githubusercontent.com/assets/7164227/11743434/bb3c3792-a007-11e5-83fe-268af3f540bc.png)

**Comment by bil-elmoussaoui** [comment] 2015-12-12 20:52
The `Gui` that shows instead of the application name is the Python file name. I will create a PR to fix this

**Comment by wa4557** [comment] 2015-12-12 21:01
I actually assigned a name to it ("Numix folders GUI") so no idea why only "Gui" is showing...

**Comment by bil-elmoussaoui** [comment] 2015-12-12 21:06
@wa4557 In Gnome and some other distros, you will need to set a WM Class to the application. And add  the WM Class value to the desktop file name ;)

**Comment by dirtydancing** [comment] 2015-12-12 21:09
Well, `Numix folders GUI` is showing in the title bar of the GUI, but not in GNOME dash. Screenshot:

![gui](https://cloud.githubusercontent.com/assets/7164227/11763882/cb260db6-a11c-11e5-822f-3d4bae348c57.png)

**Comment by bil-elmoussaoui** [comment] 2015-12-12 21:15
@dirtydancing can you modify gui & numix-folders.desktop as i did here #134 and try again ?

**Comment by dirtydancing** [comment] 2015-12-12 21:24
@bil-elmoussaoui I just checked your repo, and now `Numix Folders` is showing in GNOME dash :+1: 

![new](https://cloud.githubusercontent.com/assets/7164227/11763964/c21ffa04-a11e-11e5-8788-dbbca4a8d49d.png)

Just a very minor correction for consistency: I would suggest to have `Numix Folders GUI` with a capital "F" in "Folders" in the GUI title bar instead of the current `Numix folders GUI`, cf. above.

**Comment by bil-elmoussaoui** [comment] 2015-12-12 21:30
I will change that in my repo. Can you see if the logo is blured when you use ALT  + TAB ?

**Comment by dirtydancing** [comment] 2015-12-12 21:37
Yeah, I am afraid the icon is blurred in ALT + TAB. Screenshot:

![alt-tab](https://cloud.githubusercontent.com/assets/7164227/11764024/c23c482e-a120-11e5-92b2-b69bff590bcd.png)

**Comment by bil-elmoussaoui** [comment] 2015-12-12 21:39
@dirtydancing Do you open the application using Terminal? can you try using the desktop file?

**Comment by dirtydancing** [comment] 2015-12-12 21:47
Yes, I am using the Terminal for this. I just checked opening the .desktop file, and with that one, the old name `Gui` is back in GNOME dash as well as in ALT + TAB, and the icon in ALT + TAB is still blurry:

![desktop_file](https://cloud.githubusercontent.com/assets/7164227/11764054/0b5e8a84-a122-11e5-8463-de56fdd34605.png)

**Comment by bil-elmoussaoui** [comment] 2015-12-12 21:57
Hmm, can you change the line 123 in the gui file with this 
`self.set_wmclass("Numix Folders", "numix-folders")`
and use the desktop file again? :+1:

**Comment by dirtydancing** [comment] 2015-12-12 22:12
Changed line 123 as you suggested, but no changes, still `Gui` when using the .desktop file. Even worse, I seem to be getting `Gui` via Terminal as well now? Not sure what is going on here :). I will be able to continue this tomorrow.

**Comment by bil-elmoussaoui** [comment] 2015-12-12 22:14
I will need to install Numix Folders from ppa to be able to test this. Thanks anyway;) i will try to figure out what's not working

**Comment by wa4557** [comment] 2015-12-19 09:34
I can confirm the blurry icon when using alt+tab. I wonder what's going on here...

**Comment by bil-elmoussaoui** [comment] 2015-12-19 09:40
The blurry icons can be fixed by adding a StartupWMClass for the application in the desktop file.. And i think i know what's going on. When you open Numix-Folders and you open Gnome System monitor, the application is not detected there.. it should be, so something is still missing; I think the first thing to do is to convert the application from a normal Gtk.Window to a Gtk.Application..

**Comment by bil-elmoussaoui** [comment] 2015-12-26 12:44
Well, i figured out what's going wrong. Gnome does not detect the python file as an application but just a normal script..I fixed this issue by using autotools on a project i'm working on. 
@Foggalong As the repo does not contain anything about that, should i open a PR for that later?

**Comment by Foggalong** [comment] 2015-12-26 15:40
I'm not entirely sure what you mean, sorry :(

**Comment by bil-elmoussaoui** [comment] 2015-12-26 15:44
The desktop file opens a bash script that runs a python script. Gnome (maybe other distros too) does not detect python files as application, you need to compile the python file first. I looked at the packaging branch and the python file is not compiled

**Comment by Foggalong** [comment] 2015-12-26 15:56
don't we currently have a bash script running a python script?

**Comment by dirtydancing** [comment] 2015-12-26 17:19
Just to let you know: with the GUI enhancement pull request by @bil-elmoussaoui over at https://github.com/numixproject/numix-folders/pull/136, the application name correctly reads `Numix Folders`. Screenshot with Arch/GNOME:

![numix_folders](https://cloud.githubusercontent.com/assets/7164227/12007253/9ef74ef4-abfc-11e5-95d2-9d4c7228f6c5.png)

The icon is still blurry with ALT + TAB, though, just like already seen above.

**Comment by bil-elmoussaoui** [comment] 2015-12-26 17:25
@dirtydancing  Because i've added the `set _wmclass` to the code.  I think that we should make the python code call the  bash script and use the python script by default without having to ask the user for root permissions when he opens the application. Once we have done that we can compile the python code using Autotools. I can take care of all that if you want. I just need to pass my exams in two weeks

**Comment by dirtydancing** [comment] 2015-12-26 18:20
I am not sure what this is all about :) Seems to be working fine at my end. @Foggalong `s call I figure.

**Comment by wa4557** [comment] 2015-12-26 20:02
This is just too much work for an application that already works pretty decent. I would just keep it the way it is and change the desktop file so that the icon becomes sharp ...

**Comment by wa4557** [comment] 2015-12-31 14:51
This can be closed now...

**Closed** 2015-12-31 14:56 UTC
Labels: enhancement
