### ISSUE TITLE
Folder style does not change in nautilus bookmarks section

### ISSUE THREAD

**Issue by uloco** [numixproject/numix-folders#31] opened 2015-03-10 17:21 UTC
I recently discovered, that the script does not change the folder style in the bookmarks section of nautilus. I'm on Ubuntu 14.04 x64 and everywhere it changes but at this location. I just noticed that this is not supposed to be...

The script changes the icons in firefox, the launcher icon, the folders in nautilus, but only the bookmarks stay untouched. It also doesn't matter which style I choose, it stays the same.

![numix-folder-nautilus](https://cloud.githubusercontent.com/assets/8818340/6580573/e6afc7b6-c751-11e4-917c-6bb412141520.png)

EDIT: I am using the actual Nautilus Version 3.10.1

**Comment by dirtydancing** [comment] 2015-03-10 23:25
Quick thought: on first sight, this looks like `folder-symbolic.svg` from `scalable/places` of gnome icon theme, which is inherited by Numix icon theme.

![gnome-icon-theme](https://cloud.githubusercontent.com/assets/7164227/6587307/e1ff5584-c782-11e4-9f3c-871754fb636b.png)

What should be displayed instead is `folder-symbolic.svg` from `scalable/places` of Numix icon theme (here of folder style 5 which you are also using in your screenshot):

![numix-icon-theme](https://cloud.githubusercontent.com/assets/7164227/6587439/88815afa-c784-11e4-94c0-dc3d5d17d212.png)

I am not sure why the Numix icon is not picked up, and I can not reproduce this problem with Ubuntu 14.10. Could you simply try and force (-f) an icon cache update with the terminal command:

`sudo gtk-update-icon-cache -f /usr/share/icons/Numix`

(assuming that is your path to the Numix icon theme), and then change the icon theme (e.g. in Unity Tweak Tool) to s.th. else and back again to Numix-Circle? This might work.

**Comment by uloco** [comment] 2015-03-11 08:23
Unfortunately, this has no effect...

**Comment by dirtydancing** [comment] 2015-03-11 08:51
Ah, too bad. Well, just to make absolutely sure in case that the changing of icon themes back and forth was insufficient: did you log out and back in and further shut down and restart your machine after the icon cache update?

**Comment by dirtydancing** [comment] 2015-03-11 09:04
Very strange, on my machine, it is Ubuntu 14.10 with default Nautilus/Files 3.10.1, and I have never seen this non-Numix icon for bookmarks. This has always been the respective Numix icon so far, cf. also e.g. https://github.com/numixproject/numix-icon-theme/issues/268

**Comment by uloco** [comment] 2015-03-11 10:52
I did restart xserver and restarted my computer afterwards, nothing changed. Perhaps it is a Nautilus issue, because I have several plugins installed (meld diff view, 'Open Terminal Here' dialog in context menue, ...).
I will try to uninstall all those things and try a fresh install of nautilus. Perhaps there is a issue...

**Comment by uloco** [comment] 2015-03-11 15:49
Nope, nothing worked for me.
Switched to Nemo now and realisied that it is a much better file manager.
Perhaps you will find the bug someday...

**Comment by dirtydancing** [comment] 2015-03-12 20:45
Well, I am afraid this will remain unresolved then for the time being.

To me, this does not look like a bug in Numix, because the proper icon `folder-symbolic.svg` is in place. I just checked in current daily Ubuntu 15.04 (in development) with Nautilus 3.14.2, and the Numix icon is displayed just fine there as well.

Good to hear though that this has prompted you to switch to a file manager that suits you better :-)

![ubuntu-1504-daily_nautilus-3-14-2](https://cloud.githubusercontent.com/assets/7164227/6627761/d723f19a-c900-11e4-81dd-83b453637165.png)

**Comment by Foggalong** [comment] 2015-03-15 22:20
Aye, I'm gonna assume this is a bug with old Nautilus or old Ubuntu. Closing, but will keep an eye out for if a similar issue crops up again.

**Closed by Foggalong** 2015-03-15 22:20 UTC
