### ISSUE TITLE
Folder Color

### ISSUE THREAD

**Issue by uloco** [numixproject/numix-folders#30] opened 2015-03-09 07:50 UTC
How can I use the different folder colors now, as they are shown in the readme file?
Sorry if this is obvious, but I just don't get it...

**Comment by Foggalong** [comment] 2015-03-09 12:02
The default switcher isn't implemented yet which is why we haven't formally announced the feature yet. It should land in a day or 2 :)

**Comment by uloco** [comment] 2015-03-09 12:59
Thanks you!

**Comment by dirtydancing** [comment] 2015-03-10 13:21
Cool, a default colour switcher (I assume for all folder icons at once) will be a welcome addition to Folder-Color (currently aimed at individual folder icons)!

Just as a side note: Current Folder-Color (version 0.0.51 via PPA) is displaying non-default colour folders apparently from Humanity icon theme (Ubuntu default for folders). I figure this is known and will be updated/adapted, too.

Current screenshot with a blue, green and grey folder selected via Folder-Color in Ubuntu 14.10:

![folder-color](https://cloud.githubusercontent.com/assets/7164227/6575520/abe2fb34-c72f-11e4-9a95-3ccea953ec19.png)

**Comment by Foggalong** [comment] 2015-03-10 15:16
If you're using the latest version it should work as expected http://youtu.be/BAwEpRgI4YE

**Comment by dirtydancing** [comment] 2015-03-10 18:48
Very strange indeed, all up-to-date here (Ubuntu 14.10 with default Nautilus/Files 3.10.1), and still the Numix folders are only displayed in default colour, and when changing the colour the Humanity (Ubuntu default) folder icon is displayed.

The video link above seems to feature Ubuntu MATE (?), maybe that makes a difference?

Anyways, I went ahead and checked two things:

1) The packages in the Folder Color PPA. I manually added `ubuntu-icon-theme-switcher` (not installed by default via PPA), just to try, but that had no effect.

Synaptic screenshot:

![folder-color_synaptic](https://cloud.githubusercontent.com/assets/7164227/6582480/dceacc10-c75d-11e4-9e9c-e590e5359a72.png)

2) I switched back to the Numix default folder style with "0" in the Numix Folders script, just in case. But again, no effect:

Screenshot with Numix default folder style:

![folder-color_numix-default-style](https://cloud.githubusercontent.com/assets/7164227/6582513/02b601c6-c75e-11e4-95a2-bde5b57d4006.png)

Am I missing something obvious here?

**Comment by dirtydancing** [comment] 2015-03-10 19:15
Just double-checked: the different folder colours are present for Numix (back to style 5 again):

![numix_folder-icons](https://cloud.githubusercontent.com/assets/7164227/6583040/ad446530-c761-11e4-952b-31c57a415bf5.png)

**Comment by dirtydancing** [comment] 2015-03-10 19:48
By the way, I get the same phenomenon in (VM) Ubuntu 15.04 Vivid daily (in development) with default Nautilus/Files 3.14.2 and with folder-color 0.0.45-0ubuntu1 (current version from the official Ubuntu 15.04 repositories):

![ubuntu1504_folder-color](https://cloud.githubusercontent.com/assets/7164227/6583763/8aa8195e-c766-11e4-881b-0d94d2b44a67.png)

**Comment by dirtydancing** [comment] 2015-03-10 22:52
Ok, I just had another look into this, and the problem appears to be an inconsistent file naming convention:

As an example, I traced the plain blue folder. The `folder-color-common` package installs `folder_color_blue.svg` in `hicolor`.

![synaptic](https://cloud.githubusercontent.com/assets/7164227/6586632/4163d2f0-c77b-11e4-9a5f-42c65ed5fb74.png)

![hicolor_1](https://cloud.githubusercontent.com/assets/7164227/6586732/42b05ff6-c77c-11e4-9c21-d3aa95fefb0d.png)

This of course is a different icon name from the Numix icon. The corresponding Numix icon is named `blue-folder.svg`.

![numix_0](https://cloud.githubusercontent.com/assets/7164227/6586931/680eb6e2-c77e-11e4-84c9-2f66a6ebfa3e.png)

So to test, I copied `blue-folder.svg` and renamed the copy into `folder_color_blue.svg`

![numix_1](https://cloud.githubusercontent.com/assets/7164227/6586738/48d39e98-c77c-11e4-81c5-09252629a589.png)

I then forced an icon cache update with `sudo gtk-update-icon-cache -f /usr/share/icons/Numix`.

The result is this:

![home_1](https://cloud.githubusercontent.com/assets/7164227/6586787/c8170730-c77c-11e4-9195-782652b87a77.png)

The change of colour to blue is now possible, but the dialogue only offers blue, no other colours and not all the further options except for "By Default".

So I figure that this is a matter of co-ordinating the icon names? And currently, the icons in hicolor are displayed because Numix icon theme inherits hicolor icon theme in the end?

My recommendation would be to adapt the folder icon names that Folder-Color looks to into the names currently used by Numix. To me, the Numix naming seems more elegant, and from what I have seen there are thousands and thousands of Numix icons/icon names, whereas the number of icon names provided by folder-color-common is rather limited in comparison. Of course, all of this is just a thought and impression of mine, I cannot tell what is practical here or if this is really the root of this issue at all.

**Comment by Foggalong** [comment] 2015-03-10 23:38
Yeah, you're not running the latest version of Numix :P There are symlinks pointing from `[colour]-folder-*.svg` to `folder_color_[colour]_*.svg` in the latest version.

**Comment by dirtydancing** [comment] 2015-03-10 23:46
Haha, this is what I call an easy solution :-) Just checked, and the latest Numix base version then apparently has not landed yet in the PPA, as there were no updates available. PPA stats say that numix-icon-theme was last updated 9 days ago.

**Comment by Foggalong** [comment] 2015-03-10 23:54
Yeah, latest version in git :) I'm waiting until I've implemented the default colour switching to push the update to PPA so we can make the announcement properly

**Comment by dirtydancing** [comment] 2015-03-13 09:22
Maybe offtopic, maybe related to this question, but in any case a follow-up on my testing for this thread:

After I had deleted the blue folder that I copied to Numix base (cf. screenshot above, only blue showing as an option), the "Folder's Color" dialogue did not display anymore when right-clicking. So I deleted and reinstalled Folder Color and shutdown and rebooted my machine, but the dialogue still did not show:

![numix-circle-1](https://cloud.githubusercontent.com/assets/7164227/6635611/48b0a576-c968-11e4-8f90-281685d2c4f5.png)

In contrast, with default Ubuntu-mono-dark icon theme selected to test, the dialogue showed on right-click:

![ubuntu-mono-dark](https://cloud.githubusercontent.com/assets/7164227/6635624/6620ab92-c968-11e4-91b8-58b5b91736f2.png)

After I deleted the `folder-color` folder in `~/.config`, updated the icon cache and restarted Nautilus, the "Folder's Color" dialogue showed again on right-click (and again, because this is not the latest version of Numix base, cf. above, when changing the colour to blue the Humanity icon was shown):

![numix-circle-2](https://cloud.githubusercontent.com/assets/7164227/6635651/aabc95ae-c968-11e4-9f6e-d5224adbeaec.png)

I am not exactly sure what was going on here. To get into such a scenario might be unlikely for users, but is this the intended behaviour after manual intervention into the folder icons of an icon theme?

**Comment by costales** [comment] 2015-03-13 14:44
Hi @dirtydancing  |o/

> After I had deleted the blue folder that I copied to Numix base (cf. screenshot above, only blue showing as an option), the "Folder's Color" dialogue did not display anymore when right-clicking

That is because you didn't refresh the Numix icon cache :)


FYI: Folder Color 0.0.51 is getting **all** in a **dynamic** mode:
 * If the theme has folders (folder_color*.svg), will show them:
  * If it has custom icon, will show that entry.
  * If it has emblems, will show that emblems.
 * If the theme hasn't folders (folder_color*.svg), will show the hicolor by default.

If you want, you can test Folder Color & Numix now in an easy way (this will be the same when Numix will release into the PPA):
 * Install or update to Folder Color 0.0.51
 * Download the last (Numix icons)[https://github.com/numixproject/numix-icon-theme/archive/master.zip]
 * Overwrite the folder Numix into /usr/share/icons
 * Refresh the icon cache: sudo gtk-update-icon-cache /usr/share/icons/Numix
 * Test it :) You have to (see this)[https://www.youtube.com/watch?v=BAwEpRgI4YE]

If you have any problem, ping me :)

**Comment by dirtydancing** [comment] 2015-03-13 21:06
Hi @costales, thank you very much for your detailed explanations! And yeah, the icon cache... :-)

This is a fantastic project, so of course I was happy to do some testing. For that, I downloaded the latest Numix base and Numix-Circle from GitHub and installed them as extra icon themes, to be as free as possible to experiment.

And good news: Folder Color is working with the Numix folder icons indeed! 

And of course, some questions/observations arose along the way. This is a first testing of mine, and I am just noting down what came to my attention. Now, I have not been following the development of this collaboration in detail, so, much of this might be obvious or clarified already, in which case please just don't bother with it :-)

**1)** There is no "Custom" ("Benzutzerdefiniert" in German) option for Numix. Is this on purpose?

In contrast, there is a custom option when using Ubuntu-mono-dark (Humanity), which allows to define a custom folder colour (which then apparently is saved in `~/.config/folder-color/custom_icons`).

**2)** Am I correct in assuming that Folder Color does not work for manually selecting folder icons, more specifically for folder icons that were additionally created by Numix?

To test, I added e.g. `folder_color_blue_vm.svg`, and in consequence "Blue Vm" showed up in the Folder Options right below "Blau". I figure that this is what you referred to as "custom icon" above?

In my test, when I went back to "By Default", a plain default folder (without VM symbol) was displayed, not the original default colour folder with VM symbol; this last aspect I did not check in detail, though.

**3)** There are no emblem options showing for Numix. Is this on purpose?

To test, I added a couple of `folder_emblem_*.svg` files (in the emblems directory), and they showed up in the Folder Color options and could be added to the folders. I noticed that `folder-color-common` only adds them in size 24x24. Would they have to be added in every size for the respective folder icon size?

I figure that this could also be a Numix design decision. I was just thinking that, just like different folder colours themselves, some emblem options could be useful e.g. to optimise workflows.

**4)** S.th. I already noticed earlier and that is also visible in the screenshots above: At least in Ubuntu with default Nautilus/Files, in the Folder Color options only text is visible, not thumbnail folder icons (and emblems, if available) as in the video you referred to. This goes for all icon themes. Is this on purpose, or is this e.g. a limitation in Nautilus/Files?

**5)** In the Folder Color options, "Restore" (and "Categorize") are greyed out. What are these options needed for (and how does "Restore" differ from "By default"), and if they are not needed, would it not be better to not display them at all?

**6)** As to the German translation: apparently this has been completed for the folder colours. But as you can see in the screenshots above, the order of the colours in not alphabetical in the German colour names, but apparently is following the alphabetical order of the English colour names. Is this an intended design decision (would make sense if you want to keep the order of the colours the same in all languages)?

**7)** For Numix folder icons, a "colour" "Default" (not translated, although the other colours are translated) is displayed in the Folder Color options, in addition to the option "By Default". Could there be a clearer distinction between these two?

I believe the colour "default" is needed for the Numix folders to function, and as a result this shows up in the Folder Color options as well. Could this be made less confusing from Folder Color's side? E.g. by naming the "By Default" option "Original Folder" or the like? Then again, there is a "Restore" option, but it is greyed out, cf. **5)** above.

Or, alternatively, could Folder Color just not display a "colour" that is named "default"?

I am just wondering about this, and in the end this might not be all that confusing after all. But if I remember correctly, the options "Default" and "By Default" had different consequences when changing the icon theme after having used these options.

Thanks for staying with me through all of this :-) I am hopeful that this is of help to you in some way.

**Comment by Foggalong** [comment] 2015-03-13 21:29
The answer to Q2 is yes. You could make `folder_color_freedom_*.svg` and "Freedom would show up as an available colour. That answers Q1, and the same goes for Q3. Q7 has already been discussed privately and though a solution will eventually land there's nothing to be done right now.

**Comment by costales** [comment] 2015-03-13 22:00
Hi there! :) @dirtydancing I never had a review as your!! I'm glad to
have it :D And thanks!!
I'll try to reply all of them :)

> **1)** There is no "Custom" ("Benzutzerdefiniert" in German) option for
> Numix. Is this on purpose?

Yes, Numix will not have it in this release, then Folder Color will not show it.
An icon "folder_custom*.svg" has to exist in at least 1 resolution. If
you have really interesting in this icon, we worked in the 48x48
resolution and I can send you :)



> In contrast, there is a custom option when using Ubuntu-mono-dark
> (Humanity), which allows to define a custom folder colour (which then
> apparently is saved in `~/.config/folder-color/custom_icons`).

Yes, the icon /usr/share/icons/<theme>/<a_resolution>/places/folder_custom.svg
is copied and parched in ~/.config/folder-color/custom_icons. Because
of that, it's a hard path and it'll not change with the theme :)



> **2)** Am I correct in assuming that Folder Color does not work for manually
> selecting folder icons, more specifically for folder icons that were
> additionally created by Numix?
> In my test, when I went back to "By Default", a plain default folder
> (without VM symbol) was displayed, not the original default colour folder
> with VM symbol; this last aspect I did not check in detail, though.

Yes, it's right. I'm just covering the 'real' default folders. The
default folder which are the preinstalled with Ubuntu.
In other case, I'll think on this and I'll try to adapt to other (not)
default folders like Dropbox :) But it'll be in other release :P I
don't promise.



> **3)** There are no emblem options showing for Numix. Is this on purpose?

Yes, in this version Numix just has the regular colors. Not custom or
emblems, then Folder Color will not show them.



> To test, I added a couple of `folder_emblem_*.svg` files (in the emblems
> directory), and they showed up in the Folder Color options and could be
> added to the folders. I noticed that `folder-color-common` only adds them in
> size 24x24. Would they have to be added in every size for the respective
> folder icon size?

Any size :) Folder Color is dynamic for all, then if you create a
folder_emblem_todo.svg in the 16x16, Folder Color will find it and
show you :D




> I figure that this could also be a Numix design decision. I was just
> thinking that, just like different folder colours themselves, some emblem
> options could be useful e.g. to optimise workflows.

Remember that with dynamic way for Folder Color, Numix can improve the
icons in the future :D And remember, to adapt the icons for Folder
Color was a really big work (+1000 icons :S). Cheers for Numix
deverlopers!!



> **4)** S.th. I already noticed earlier and that is also visible in the
> screenshots above: At least in Ubuntu with default Nautilus/Files, in the
> Folder Color options only text is visible, not thumbnail folder icons (and
> emblems, if available) as in the video you referred to. This goes for all
> icon themes. Is this on purpose, or is this e.g. a limitation in
> Nautilus/Files?

This is an older Ubuntu choice. They removed the icons in menus & buttons.
My video is in MATE and it has icons in menus & buttons (Xubuntu has them too).
You can change this behavior with for instance, Ubuntu Tweak.




> **5)** In the Folder Color options, "Restore" (and "Categorize") are greyed
> out. What are these options needed for (and how does "Restore" differ from
> "By default"), and if they are not needed, would it not be better to not
> display them at all?

Yes, it's a 'separator'. I can't add a real separator (or I don't know
:$), then I used that tip.


> **6)** As to the German translation: apparently this has been completed for
> the folder colours. But as you can see in the screenshots above, the order
> of the colours in not alphabetical in the German colour names, but
> apparently is following the alphabetical order of the English colour names.
> Is this an intended design decision (would make sense if you want to keep
> the order of the colours the same in all languages)?

I think you found a bug :) They has to be in an alphabetical sort.
I'll review it! Thanks for the detail!! :D


> **7)** For Numix folder icons, a "colour" "Default" (not translated,
> although the other colours are translated) is displayed in the Folder Color
> options, in addition to the option "By Default". Could there be a clearer
> distinction between these two?

"Default" is not a default color in Folder Color, it's a new color,
then as dynamic color hasn't translation.




> I believe the colour "default" is needed for the Numix folders to function,
> and as a result this shows up in the Folder Color options as well. Could
> this be made less confusing from Folder Color's side? E.g. by naming the "By
> Default" option "Original Folder" or the like? Then again, there is a
> "Restore" option, but it is greyed out, cf. **5)** above.

"Restore" is the title for "By default". Yes, Numix wanted that
behavior and I'll respect that :) I think I'll not change the current
Folder translation, because other themes could not have "Default"
color then ;)



> I am just wondering about this, and in the end this might not be all that
> confusing after all. But if I remember correctly, the options "Default" and
> "By Default" had different consequences when changing the icon theme after
> having used these options.
>
> Thanks for staying with me through all of this :-) I am hopeful that this is
> of help to you in some way.


A lot :D Really!!! It's lovelly have users like you :D I own you a beer! ;)
Cheers!

**Comment by dirtydancing** [comment] 2015-03-13 22:54
@Foggalong and @costales Thanks a lot for your clarifications, I am really looking forward to the official announcement now! And I like to think that I am somewhat aware of how much work this has been so far, so definitely cheers for that :-)

@costales Actually, personally I am happy with the design decisions by Numix (and also by Ubuntu), so I will just go along with that, no need for me to manually intervene.

Just a quick feedback regarding the text lines as "separators":

As it stands currently, to me this represents a kind of usability issue, because normally the "greyed out" text is an option that is simply not available in the present context. But not to worry, here are two more thoughts:

**1)** If these are supposed to be "titles", then to be consistent, you could add `Colors` or possibly even clearer `Available Colors` at the very top as the first line above all the colours, so users will know that the "greyed out" text lines are introducing a new section.

**2)** If possible, you could add a ":" at the end of the "greyed out" lines, to make clear that this is an introductory title for what is to follow (esp. useful when the file manager is not displaying thumbnail icons). So these text lines could look like this:

`Available Colors:` (or `Colors:`)
...
`Restore:`
...
`Categorize:` (this goes for the emblems, if available)
...
`Support this app:`
...

**Comment by dirtydancing** [comment] 2015-03-13 23:01
Ah, just realising that the "titles" are all action-oriented, so the name of the very first line could also be `Choose a color` or `Select a color`.

**Comment by dirtydancing** [comment] 2015-03-14 07:13
Hah, here is another term for the first "title" that just crossed my mind, and that might fit even better with the other terms and appears more fun, engaging and expanding (if suitable in the English language):

`Colorize`

So you would have the triple action `Colorize`, `Restore`, `Categorize`, and additionally `Support this app`.

These "action titles" are starting to get even better than the originally intended plain "separators"... :-)

**Comment by dirtydancing** [comment] 2015-03-14 07:35
And it might be worth considering to place "Categorize" (only showing if emblems are found) after "Colorize" and before "Restore", because "Restore" resets everything back to the original folder design, including the emblems. 

The way it is currently, with "Restore" inbetween the colours and the emblems, is somewhat unclear because one might think that "Restore" only applies to the colour.

**Comment by costales** [comment] 2015-03-14 10:21
Hi there! :)

> If these are supposed to be "titles", then to be consistent, you could add Colors or possibly even clearer Available Colors

I was thinking in that a few months ago. I'd like to avoid it, because the menu has a really big height now :S  In other way, if the user clicks "Folder's Color" menu and he sees colors as first items... It's obvious :P
My point of view is this behavior:
Folder's Color > You see those colors
Extra actions: Restore, Categorize & Support this app.


> If possible, you could add a ":" at the end of the "greyed out" lines

Good idea! Done :)


>  place "Categorize" (only showing if emblems are found) after "Colorize" and before "Restore", because "Restore" resets everything back to the original folder design, including the emblems. 

Well see ;) Done :)

FYI: You'll see untranslated those strings until a user translates it [here](https://translations.launchpad.net/folder-color/trunk) and I release them when a bug exists.


I released those changes now into the PPA. Version 0.0.52!
For update, run in a Terminal:
sudo apt-get update && sudo apt-get install folder-color

About the custom icon in Numix, if you want to try, you can download it from [here](https://copy.com/zql3RumybDSMV4nW) and copy it into the Numix folder:

    sudo cp folder_custom.svg /usr/share/icons/Numix/48x48/places/
    sudo gtk-update-icon-cache /usr/share/icons/Numix

Then, a custom icon will appear into Folder Color ;) But it'll be just for a regular custom, I want to say: You'll not have icons inside folders like "Documents", "Downloads"... You should need a folder_custom_documents.svg, folder_custom_downloads.svg, etc ;)

Thank you a lot @dirtydancing for your feedback!!

**Comment by dirtydancing** [comment] 2015-03-14 16:38
@costales Great! I just updated to PPA version 0.0.52, and I am already in the course of experiencing the improvements.

I see your point with Folder's Color > colours coming up right away, and with the menu getting too high. Actually, for me the added ":" do the trick: I am not wondering anymore why `Restore` is a disabled option, but in contrast I realise that `Restore:` is not an option at all, but rather pointing to `By Default`.

When I first checked the emblem feature of Folder Color, I wondered if this could get reverted and was a little hesitant to try it. Now with `Restore:` below the colours and below `Categorize:`, all is clear, no hesitation anymore.

And I see that the German translated colour names are now displayed alphabetically on their own.

Also, thanks for providing the folder_custom icon. I used it in a test icon theme (I am using Numix folder style 5, and this folder_custom icon is Numix default folder style 6), and it worked! 

![folder_custom](https://cloud.githubusercontent.com/assets/7164227/6652422/43cf2ce2-ca6e-11e4-8456-fc75aab6332c.png)

**Comment by costales** [comment] 2015-03-14 16:44
I'm really glad of users like you! |o/ Cheers and thanks for the feedback!

**Comment by dirtydancing** [comment] 2015-03-14 22:09
Just to let you know: I have suggested German translations for all the missing strings over at Launchpad. This will now need to be reviewed. I am not familiar with this process, but I hope this review will happen in due time.

Thank you for pointing me to the relevant Launchpad page. Looking forward to a completed German version of Folder Color :-)

**Comment by dirtydancing** [comment] 2015-03-14 22:22
And I have a question regarding the upcoming Ubuntu 15.04: Will there be a more recent version of Folder Color in the official repositories of the final release of Ubuntu 15.04 than currently Folder Color version 0.0.45?

**Comment by costales** [comment] 2015-03-14 22:24
Great! They will entry with the next release :) thanks a lot!!



-- 
Sent using Dekko from my Ubuntu device

**Comment by costales** [comment] 2015-03-15 08:28
> Will there be a more recent version of Folder Color in the official
repositories of the final release of Ubuntu 15.04 than currently Folder
Color version 0.0.45?

I'm trying that, but Ubuntu 15.04 is freeze for QA now :O

**Comment by dirtydancing** [comment] 2015-03-15 10:07
Right, that's what I thought for Ubuntu 15.04. I was just being curious. Anyways, of course there is always the up-to-date Folder Color PPA, and seeing how Folder Color is constantly improving, the PPA looks like the way to go anyways.

And wow, I just saw over at Launchpad that the German language translation for Folder Color is now officially complete. Great, and what a good occasion for my very first contribution on Launchpad (apart from the occasional bug report over there)! So I learned s.th. along the way as well. I hope that many more languages will follow.

I have already started to make use of Folder Color. I find it really useful esp. when I have many folders in one directory, and I want to see right away in which stage a certain project is, or to highlight a certain folder. And this is not even accounting for the fun part of playing with some colours :-)

And for my personal design preferences, the collaboration with Numix takes this to an entirely new aesthetic level. There is a lot of work behind it, and it is almost getting ridiculous how aesthetically advanced (functionally advanced anyways) the Linux desktop is these days :-). Yeah!

**Comment by dirtydancing** [comment] 2015-03-19 12:35
Quick update: Good to see that by now, the "colour" "Default" is not displayed in the selection of colours anymore, and that rather "Default" is only displayed under "Restore:".

That improves usability and answers my Q7 from above.

Screenshot (Ubuntu 14.10):

![folder-color](https://cloud.githubusercontent.com/assets/7164227/6730247/f7387c6e-ce3a-11e4-902c-9d5986799fca.png)

Currently, I am running into some difficulties in detail with the "Global Color" feature, esp. relating to manually selected folders and to folder sizes other than 48x48, but that is another topic.

This is getting better and better, keep up the great work!

**Comment by dirtydancing** [comment] 2015-03-21 20:28
@uloco This comment of mine over at Numix base ties in with the conversation here and might be of interest to you: https://github.com/numixproject/numix-icon-theme/issues/304#issuecomment-84445092

**Comment by Foggalong** [comment] 2015-04-30 12:49
As of 901b1dc47502fbf6ad6c013cbd6dfc4e7d2d015e this option is now available in the script. We're still working out a few bugs here and there but it looks like it will be announced formally soon :)

**Closed by Foggalong** 2015-04-30 12:49 UTC
Labels: question

**Comment by bfranklyn** [comment] 2015-06-19 13:36
There is still no way to change folder colors using the script, at least not an obvious one.

**Comment by Foggalong** [comment] 2015-06-19 13:43
Unless you're running a very outdated version, it's impossible to miss.

**Comment by dirtydancing** [comment] 2015-06-19 14:06
Huh? I have been using this for quite a while now, and this is possible very smoothly. I figure this is because numix-folders has not been officially announced yet. Just lately, still a "hidden" bug was fixed and some enhancements were merged in.

To let you know: the script asks for the folder style (1-6, cf. the readme for an overview) and for the folder colour. For the colour, you have several possibilities, e.g. the predefined colours such as `blue, brown...`, and also `custom`, which will give you the possibility to enter individual color hex values for primary, secondary and symbol colour. Moreover, you can also apply the default colours of one folder style to another folder style (`style1 to style6`). Hitting enter without specifying a colour will get you the respective default colour.

To illustrate, here is a screenshot of my current folder style in Arch/GNOME, all default except the icon theme, some additional folder icons and the folder style (folder style 5 with custom colours):

![folder-style](https://cloud.githubusercontent.com/assets/7164227/8254946/a4722642-169c-11e5-9481-1750cdc8cfd8.png)

**Comment by bfranklyn** [comment] 2015-06-19 16:36
Thanks guys I updated and it's working fine now.

**Comment by Foggalong** [comment] 2015-06-19 16:37
@bfranklyn No problem! Glad to hear it's working for you :)

**Comment by dirtydancing** [comment] 2015-06-19 21:58
@bfranklyn :+1:
