### ISSUE TITLE
Include numix-folders in the Numix PPA

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-folders#47] opened 2015-04-13 16:10 UTC
Question: Would it be manageable and reasonable to include the numix-folders package in the Numix PPA? Reasons:

1) This way, there would be no need for users to check back here on GitHub for updates.

2) numix-folders is supposed to be located in the same directory as Numix base anyways.

3) And additionally, this would give some more exposure to the awesome Numix Folders project :)

**Comment by Foggalong** [comment] 2015-04-13 17:16
I'm not 100% sure how packaging would work with regard to the script, but I'll ask Paolo once the colour switching is implemented :)

**Comment by Foggalong** [comment] 2015-06-19 16:42
@dirtydancing I've done the transfer for the custom colours and book icons to base, now it's just a case of testing that the PPA works okay :)

**Comment by wa4557** [comment] 2015-06-19 16:46
@Foggalong Not entirely #76 is still valid :)

**Comment by Foggalong** [comment] 2015-06-19 16:48
That's part of testing that the PPA works okay :)

**Comment by wa4557** [comment] 2015-06-19 16:54
Btw: I think you lost a few icons along the way: `*folder-books.svg` is only there in 16x16 for all colours and only `custom-folder-books.svg` is there for all the other sizes

**Comment by Foggalong** [comment] 2015-06-19 16:56
Which style? I might have missed a few :)

**Comment by wa4557** [comment] 2015-06-19 16:58
In `numix-icon-theme` there are missing these icons, therefore it's style 6 of course :)

**Comment by Foggalong** [comment] 2015-06-19 17:01
ahhh, I see what you mean! Good catch, I'll get on that now

**Comment by dirtydancing** [comment] 2015-06-19 21:50
@Foggalong Great news! For this grand occasion, I have a Xubuntu 15.04 VM waiting to test the PPA :)

**Comment by Foggalong** [comment] 2015-06-19 22:49
@dirtydancing all the stuff is pushed so let us known if it works :)

**Comment by dirtydancing** [comment] 2015-06-20 08:36
OK, first impressions with a fresh Xubuntu 15.04 (VM), only change adding the Numix PPA and installing numix-icon-theme, numix-icon-theme-circle and numix-folders (numix-gtk-theme automatically detected an update):

**1)** The second gtk-update-icon-cache is reported as invalid.

I figure this relates to the PPA version of Numix-Circle (back from February 7) and is expected, and apparently this does not cause any problems with numix-folders (icon cache also reported as invalid when installing Numix-Circle, known issue from the past). Still, users might be irritated by this.

**2)** There does not seem to be the complete set of custom folder icons in size 16x16 in Numix base.

Only these custom folder icons are present in 16x16/places:

`custom-fileopen.svg`
`custom-folder.svg`
`custom-folder-copy.svg`
`custom-folder-move.svg`
`custom-folder-open.svg` (symlink pointing to `custom-fileopen.svg`)

In contrast, the Numix base version I am running on my bare metal Arch/GNOME includes all the icons. Not sure what is going on there. This means that for custom 16x16 folders, scaled down larger folder icons are displayed, but not the proper ones. This is also an inconsistency because for the default colour and for the predefined colours, all the folder icons seem to be present in size 16x16.

**Comment by dirtydancing** [comment] 2015-06-20 09:24
**3)** Not sure if this is an issue or not: When changing back to the default colour, apparently now the symlink `custom-folder-open.svg` is pointing to the target `default-fileopen.svg`. Also, `custom-fileopen.svg` now is the icon that `default-folder-open.svg` is expected to be, but `default-folder-open.svg` itself is a symlink with the target `default-fileopen.svg`. I am confused now, taking a break :)

**Comment by Foggalong** [comment] 2015-06-20 13:22
1. Is this to do with the PPA just being out of date, or is the same problem in git too?

2. That could just be a case of the `numix-icon-theme` package being a little out of sync. The git version I'm using has it which is why the AUR version will have it too.

3. That's very confusing. Sounds like some symlinks or file names have gotten muddled along the way.

**Comment by dirtydancing** [comment] 2015-06-20 14:22
1. No problem in git, so to me this looks just like the `circle` PPA being out of date.

2. I see. So this might just take another check once with the next `numix-icon-theme` PPA build.

3. I am not really sure what is going on there. Will need to take a fresh look :)

**Comment by dirtydancing** [comment] 2015-06-20 17:29
Here we go! After updating to the newest `numix-icon-them` PPA build from a couple of hours ago, now everything is working. :+1: 

1. Still present (of course, as `circle` has not updated via PPA). Does no harm.

2. All fine.

3. Not reproducible, all fine. Possibly was related to 2., or I was hallucinating :)

Next step: I will do some more checks and also bring Folder Color in via PPA for individual folder colours.

**Comment by dirtydancing** [comment] 2015-06-20 18:42
**4)** I am running into a problem/limitation that might already be known (?): When e.g. choosing folder style 1 and entering `style5` as folder colour, the folders in the default folder sizes will turn to style 5 orange, but not the folders in sizes 16x16 (only the plain folder will turn style 5 orange, the rest will stay in the previous colour). This inconsistency happens via PPA as well as via git. I would expect the primary orange colour of style 5 to be used for all folder sizes, but apparently that is currently not happening.

Can someone reproduce this?

**Comment by dirtydancing** [comment] 2015-06-20 19:01
**5)** Alas, upon further inspection I am again running into s.th. that reminds me of 2. above: When selecting a custom colour, in Numix base `default-folder-open.svg` turns into a symlink pointing to `custom-fileopen.svg`. When then returning to the default colour, `default-folder-open.svg` turns into a symlink pointing to `default-fileopen.svg`. Strangely enough, apparently this only happens via PPA, not via git (in my Arch/GNOME setting, `default-folder-open.svg` just remains an icon, no symlink here).

Can someone reproduce this?

**Comment by dirtydancing** [comment] 2015-06-20 20:07
Checked Folder Color via PPA for Nautilus: all seems to work fine with colours for individual folders (only the predefined colours can be selected, and no global colour option with Folder Color, all fine).

**6)** This only happens when selecting a `custom` colour twice in a row (different colours): the folder icons in size 16x16 stay in the first custom colour (except for the plain folder icons), just like in 4. above. Somehow the first custom colour is staying on also for further other custom colours. In contrast, e.g. selecting the default colour or a predefined colour will work for all folders in size 16x16. This happens via PPA as well as via git.

Can someone reproduce this?

**Comment by wa4557** [comment] 2015-06-20 20:26
@Foggalong @dirtydancing **4** and **6** (probably even **5**, not sure about that) happens, because it is necessary that the `custom-` folders stay in the numix-folder repo in `16x16`. By keeping them there the `custom` folders are overwritten each time the script is run and the correct colour can be replaced once again

**Comment by dirtydancing** [comment] 2015-06-20 20:48
@wa4557 Yeah, makes sense. I do not recall having come across **4** and **6** before, when the `custom-` folders were still located in the numix-folder repo in 16x16.

As to **5**: I have concluded the testing session for now, but this was occuring in different folder sizes, not limited to size 16x16, iirc correctly at least also in 48x48.

**Comment by Foggalong** [comment] 2015-06-20 21:15
@wa4557 ah, so the string change happens pre-copy rather than post copy?

**Comment by wa4557** [comment] 2015-06-21 06:08
No it happens post copy. But you need overwrite the changed icons if you want to change colours again, so the icons need to be in the source destination

**Comment by dirtydancing** [comment] 2015-06-21 07:19
**7)** (just keeping up the numbering): It might be useful for users to be informed that numix-folders via PPA is installed in `/opt`. When manually "installing" numix-folders, I tend to place it in `/usr/share/icons`. I guess I do so because the readme says "To use the script simply download this repo, move into the repos directory and then run the script." That might be clarified.

**8)** Moreover, in combination with **7**, it might be useful for users to be informed of how the "run the script" with a terminal command. E.g. `sudo ./numix-folders` (sudo probably depending on local/global icon theme). As far as I can tell, there is no .desktop file for numix-folders, so it does not show up in the application overview and users will arguably need some instruction/guideline on this.

**Comment by wa4557** [comment] 2015-06-21 08:23
@dirtydancing I can reproduce **5** but I have no idea what's going on there :(

**Comment by wa4557** [comment] 2015-06-21 08:53
I figured it out: The problem is that when using `cp` the command follows the symlinks, which means it does not overwrite the file itself, but rather the  file the symlink points to. `--remove-destination` fixes this problem

**Comment by dirtydancing** [comment] 2015-06-21 09:04
@wa4557 Any idea why **5** happens only via PPA and not via git? Possibly this is somehow related to **4** and **6**? Anyways, I figure upcoming PPA builds will tell.

**Comment by wa4557** [comment] 2015-06-21 09:06
I think it happens via PPA and git, but it only happens if you tried style 3 before, because it's the only style using symlinks for those specific icons...

**Comment by dirtydancing** [comment] 2015-06-21 09:07
Actually **4** and **6** are happening via PPA and via git, so that should not be related to **5** (?).

Ah, just seeing your latest comment. That makes sense. iirc I tested style 3 via PPA, but not via git again.

**Comment by dirtydancing** [comment] 2015-06-21 09:13
Just reproduced **5** via git as well, after selecting style 3. Confirmed that this is not a PPA-specific issue.

**Comment by wa4557** [comment] 2015-06-21 09:18
as for **7** do you really think it is necessary for users to know where the script is installed? After all that's a pretty useless information for most of the users, and there's a executable in `$PATH` (`/usr/bin/numix-folders` after installing via ppa)

**8**) yes that's probably a good idea

**Comment by dirtydancing** [comment] 2015-06-21 09:35
**7**: "numix-folders" is not only the script name, but also the directory name: and as the numix-folders directory also contains all the folder icon files, I believe it is useful to know where they are located, esp. when a user has all the other Numix icon files from `numix-icon-theme` and `numix-icon-theme-circle` via PPA located in `/usr/share/icons`. But then again, I agree that this might cause confusion relating to the "numix-folders" script.

**Comment by dirtydancing** [comment] 2015-06-21 09:49
**8**: When running `numix-folders` or `sudo numix-folders`, "not found" is displayed at the end of the line before "Which folder style do you want?" comes up. Is this expected? This might be irritating for users.

Terminal screenshot:

![xubuntu1504_test](https://cloud.githubusercontent.com/assets/7164227/8271211/61612cac-180b-11e5-9248-ce5c1fae9092.png)

**Comment by wa4557** [comment] 2015-06-21 09:51
@dirtydancing See #76 I reported that already

**Comment by dirtydancing** [comment] 2015-06-21 09:53
@wa4557 Haha, good call :+1: 

And yes, this definitely needs to be fixed because this might look to users like this is somehow broken.

**Comment by dirtydancing** [comment] 2015-06-21 11:26
@wa4557 Concerning **5**: I just ran the numix-folder version you modified in https://github.com/numixproject/numix-folders/pull/97

https://github.com/wa4557/numix-folders/tree/syml

with a fresh Numix base/Numix-Circle, and when I e.g. select style 3 and pink, `default-folder-open.svg` still turns into a symlink, with the target `pink-fileopen.svg`. So the problem is not fixed?

Can you reproduce this?

**Comment by wa4557** [comment] 2015-06-21 11:28
Yeah but that's intentional (if you look at the source files in `numix-folders`), for all the other styles however this should be a regular file

**Comment by dirtydancing** [comment] 2015-06-21 11:33
Ah ok. And indeed, when after that selecting e.g. folder style 5 with a custom colour, then indeed e.g. `default-folder-open.svg` turns back into the correct file (not symlink). And all files are looking fine now.

So: confirmed that https://github.com/numixproject/numix-folders/pull/97 fixes **5** :+1:

**Comment by Foggalong** [comment] 2015-06-21 16:28
7) definitely a won't fix. It would be arguably more confusing for the user to have that information since this isn't your standard icon theme.

8) I'm struggling to imagine the situation in which the user *wouldn't* know how to do this. If they've installed via PPA then they're already using a terminal and so have at least a basic understanding of how to run commands, they one they need being the name of the package just installed. If they're 
installing via GitHub and they don't know how to run scripts then we've got bigger problems :p

As an aside we've talked a bit about making a very basic GUI for this since it would help users with some of the more non-intuitive like picking colours. At the moment to use the script they have to have at least a basic understanding of colour codes which is hardly a noob skill.

**Comment by wa4557** [comment] 2015-06-21 16:32
@Foggalong I was thinking about makeing a gui as well (the color picker etc. would be pretty cool). Zenity or gtkdialog would be sufficient imo

**Comment by dirtydancing** [comment] 2015-06-21 17:34
A GUI with a color picker would be very useful indeed.

I do not know how much effort this would require, but imo it would also be useful to be able to save a certain style/color configuration which could then be run "automatically" when running the script again. Currently, after every Numix base update, it is necessary to run the script again and enter the folder style and for the folder colours possibly "custom" as well as 3 hex colour values.

As to **8)** I would imagine that users know how to add the Numix PPA via Terminal because there are loads of instructions containing the exact commands that need to be entered. Without any instruction on how to run the script, they could get stuck, or would need to look up somewhere else how to proceed.

**Comment by Foggalong** [comment] 2015-06-30 21:35
@dirtydancing @wa4557 how does this stack up now 2f0e0da903e763dad7f98bc9eb49d7756bc1c5bf has been pushed?

**Comment by wa4557** [comment] 2015-07-01 05:57
Works :+1:

**Comment by dirtydancing** [comment] 2015-07-01 17:47
Checked against Xubuntu 15.04 (VM) with `numix-folders`, `numix-icon-theme` and `numix-icon-theme-circle` installed via the Numix PPA: all is working now with folder style 3 and with the custom colours, so issue **5** from above appears to be fixed now :+1: 

Of course, there are still the already known issues about the "not found" line and the invalid icon cache update for (the outdated PPA version of) Numix-Circle. Terminal screenshot:

![xubuntu_1504](https://cloud.githubusercontent.com/assets/7164227/8460703/22824a88-2027-11e5-90c7-9138c2d6d087.png)

**Comment by dirtydancing** [comment] 2015-07-02 12:24
The "not found" line has been fixed, cf. https://github.com/numixproject/numix-folders/issues/76#issuecomment-118012972 :+1:

**Comment by Foggalong** [comment] 2015-07-02 13:59
@dirtydancing am I right in thinking it's just the cache thing to fix?

**Comment by wa4557** [comment] 2015-07-02 14:11
The Cache thing will be fixed as soon as you start pushing new versions of circle to the ppa
This is not a folder issue anymore i guess :)

**Comment by dirtydancing** [comment] 2015-07-02 14:11
Yes (and only for Numix-Circle via PPA, as the cache issue has already been fixed in git, https://github.com/numixproject/numix-icon-theme-circle/commit/32317d5f9833a6737d3e006edcc1e75928e641d9).

**Comment by dirtydancing** [comment] 2015-07-02 14:11
@wa4557 Agreed.

**Comment by Foggalong** [comment] 2015-07-02 14:12
:+1: awesome

**Comment by dirtydancing** [comment] 2015-07-17 07:25
To confirm: The Numix-Circle PPA is updating just fine, and when running numix-folders there is no "invalid cache" display anymore :+1:

So, imo Numix Folders is ready to be officially announced, and further enhancements (such as GUI with a colour picker, possibly saving settings) could be made along the way.

**Closed** 2015-08-23 18:48 UTC
Labels: question
